FROM node:16-alpine as STAGE_ONE

WORKDIR /home/node/app

COPY . .
 
ARG RETHINK_DB_HOST=$RETHINK_DB_HOST
ARG RETHINK_DB_PORT=$RETHINK_DB_PORT
ARG RETHINK_DB_PASSWORD=$RETHINK_DB_PASSWORD
ARG RETHINK_DB_DB=$RETHINK_DB_DB
ARG RETHINK_DB_TABLE_NAME=$RETHINK_DB_TABLE_NAME
ARG POSTGRES_DATABASE_HOST=$POSTGRES_DATABASE_HOST
ARG POSTGRES_DATABASE_PORT=$POSTGRES_DATABASE_PORT
ARG POSTGRES_DATABASE_USER=$POSTGRES_DATABASE_USER
ARG POSTGRES_DATABASE_PASSWORD=$POSTGRES_DATABASE_PASSWORD
ARG POSTGRES_DATABASE_DB=$POSTGRES_DATABASE_DB
ARG REDIS_HOST=$REDIS_HOST
ARG REDIS_PORT=$REDIS_PORT
ARG PORT_APP=$PORT_APP

RUN echo RETHINK_DB_HOST=$RETHINK_DB_HOST >> .env
RUN echo RETHINK_DB_PORT=$RETHINK_DB_PORT >> .env
RUN echo RETHINK_DB_PASSWORD=$RETHINK_DB_PASSWORD >> .env
RUN echo RETHINK_DB_DB=$RETHINK_DB_DB >> .env
RUN echo RETHINK_DB_TABLE_NAME=$RETHINK_DB_TABLE_NAME >> .env
RUN echo POSTGRES_DATABASE_HOST=$POSTGRES_DATABASE_HOST >> .env
RUN echo POSTGRES_DATABASE_PORT=$POSTGRES_DATABASE_PORT >> .env
RUN echo POSTGRES_DATABASE_USER=$POSTGRES_DATABASE_USER >> .env
RUN echo POSTGRES_DATABASE_PASSWORD=$POSTGRES_DATABASE_PASSWORD >> .env
RUN echo POSTGRES_DATABASE_DB=$POSTGRES_DATABASE_DB >> .env
RUN echo REDIS_HOST=$REDIS_HOST >> .env
RUN echo REDIS_PORT=$REDIS_PORT >> .env
RUN echo PORT_APP=$PORT_APP >> .env
 


RUN apk add yarn tzdata \
  && yarn --production && yarn build

FROM node:16-alpine as STAGE_TWO

WORKDIR /home/node/app

COPY --from=STAGE_ONE /home/node/app/dist .
COPY --from=STAGE_ONE /home/node/app/.env .env
COPY --from=STAGE_ONE /home/node/app/node_modules node_modules
COPY --from=STAGE_ONE /home/node/app/package.json package.json

EXPOSE $PORT_APP

CMD ["node","index.js"]
